---

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "g++"
    - "zip"
    - "build-essential"
    - "libglib2.0-dev"

- name: Download zip
  get_url:
    url: "https://github.com/BenLangmead/bowtie2/archive/v{{ VERSION }}.tar.gz"
    dest: "/tmp/bowtie2.tar.gz"

- name: Unzip the package
  unarchive:
    src: "/tmp/bowtie2.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Build executables from source
  make:
    chdir: "/tmp/bowtie2-{{ VERSION }}"
    params:
      NO_TBB: 1

- name: Move executable files to path
  copy:
    remote_src: yes
    src: "/tmp/bowtie2-{{ VERSION }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
  with_items:
    - "bowtie2"
    - "bowtie2-align-s"
    - "bowtie2-align-l"
    - "bowtie2-build"
    - "bowtie2-build-s"
    - "bowtie2-build-l"
    - "bowtie2-inspect"
    - "bowtie2-inspect-s"
    - "bowtie2-inspect-l"

- name: Remove temporary files
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "/tmp/bowtie2.tar.gz"
    - "/tmp/bowtie2-{{ VERSION }}"
